import { renderToStaticMarkup } from "react-dom/server";
import { describe, expect, it } from "vitest";
import { TRADE_TAXONOMY } from "@/core/trade-taxonomy";
import { resolveDemoSite, WebsiteDemoPage } from "@/features/website-renderer";

/**
 * THE GENERATOR DEMO OBEYS ITS LAWS (PRD-007 §3.5, proposed ADR-070).
 *
 * The demo route serves a site built by the production chain for any trade
 * and town a visitor names. Its claims are the flagship's claims — the
 * same functions that build customer sites; run it twice, get the same
 * site — so each is pinned here rather than trusted: determinism to the
 * byte, taxonomy-exact trade resolution (ADR-066), hard town sanitisation
 * (visitor-typed words end up inside generated headings), the permanent
 * Example strip, and the renderer's own fingerprint.
 */

describe("resolution — exact ids and sanitised towns, or nothing", () => {
  it("resolves an exact taxonomy id", () => {
    const resolved = resolveDemoSite({ trade: "roofing", town: "leeds" });
    expect(resolved).not.toBeNull();
    expect(resolved!.definition.id).toBe("roofing");
    expect(resolved!.town).toBe("Leeds");
    expect(resolved!.businessName).toBe("Example Roofing");
  });

  it("never resolves free text, close misses, or the substring trap", () => {
    for (const trade of [
      "roofer", // free text — the fuzzy matcher must not touch URLs
      "damp", // prefix of a real id
      "roofing-", // trailing junk
      "ROOFING SERVICES",
      "unclassified",
      "",
    ]) {
      expect(resolveDemoSite({ trade, town: "leeds" }), trade).toBeNull();
    }
    // Uppercase of an exact id is forgiven — it is the same id, not a guess.
    expect(resolveDemoSite({ trade: "ROOFING", town: "leeds" })).not.toBeNull();
  });

  it("sanitises the town hard — letters, spaces, hyphens, apostrophes only", () => {
    expect(resolveDemoSite({ trade: "roofing", town: "newcastle-upon-tyne" })!.town).toBe(
      "Newcastle Upon Tyne",
    );
    expect(resolveDemoSite({ trade: "roofing", town: "bishop's stortford" })!.town).toBe(
      "Bishop's Stortford",
    );
    for (const town of [
      "leeds<script>",
      "york2",
      "a", // too short
      "x".repeat(41), // too long
      "  ",
      "york%20",
    ]) {
      expect(resolveDemoSite({ trade: "roofing", town }), town).toBeNull();
    }
  });

  it("every taxonomy trade resolves — the demo covers all 35", () => {
    for (const trade of TRADE_TAXONOMY) {
      expect(resolveDemoSite({ trade: trade.id, town: "york" }), trade.id).not.toBeNull();
    }
  });
});

describe("the demo is the production chain, deterministically", () => {
  const markup = () =>
    renderToStaticMarkup(
      <WebsiteDemoPage
        resolved={resolveDemoSite({ trade: "roofing", town: "leeds" })!}
      />,
    );

  it("run it twice, get the same site — byte-identical", () => {
    expect(markup()).toBe(markup());
  });

  it("carries the renderer's own fingerprint — this is renderPage output, not a mock", () => {
    expect(markup()).toContain("data-primitive=");
  });

  it("different towns produce different sites; the same request never drifts", () => {
    const leeds = markup();
    const york = renderToStaticMarkup(
      <WebsiteDemoPage
        resolved={resolveDemoSite({ trade: "roofing", town: "york" })!}
      />,
    );
    expect(leeds).not.toBe(york);
    expect(york).toContain("York");
  });
});

describe("the example says so, and leaks nothing internal", () => {
  const html = renderToStaticMarkup(
    <WebsiteDemoPage
      resolved={resolveDemoSite({ trade: "electricians", town: "sheffield" })!}
    />,
  );

  it("the permanent truth strip is present", () => {
    expect(html).toContain("generated by TITAN for demonstration");
    expect(html).toContain("Not a real business");
  });

  it("the business is named an example by construction", () => {
    expect(html).toContain("Example");
  });

  it("public-mode redaction holds — no internal blueprint direction in the markup", () => {
    // The same law public-render.test.tsx pins for published sites: the
    // blueprint's internal annotations never reach a public document.
    expect(html).not.toMatch(/data-internal|blueprint-note|strategy-rationale/);
  });

  it("the customer-facing trade string reaches the page — never the operational label", () => {
    // The archetype sweep caught "PLUMBING & HEATING (EMERGENCY)" in a
    // generated subtitle: the taxonomy's operational label leaking into
    // customer-facing chrome (ADR-061's exact distinction). The demo now
    // feeds customerName to the generator; the parenthetical can't return.
    const emergency = renderToStaticMarkup(
      <WebsiteDemoPage
        resolved={
          resolveDemoSite({ trade: "plumbing-heating-emergency", town: "manchester" })!
        }
      />,
    );
    expect(emergency).not.toMatch(/\(emergency\)/i);
    expect(emergency).not.toMatch(/\(private\)/i);
  });
});
