import { generateExperienceStrategy } from "@/core/experience-strategy";
import {
  buildWebsiteBlueprint,
  type WebsiteBlueprint,
} from "@/core/website-blueprint";
import { getTradeDefinition, type TradeDefinition } from "@/core/trade-taxonomy";
import { renderPage } from "../model/render-page";
import { rendererFontClass } from "../theme/fonts";

/**
 * The generator demo (PRD-007 §3.5) — the flagship's climax as a document.
 *
 * A visitor names a trade and a town; this page runs the EXACT production
 * chain — `generateExperienceStrategy` → `buildWebsiteBlueprint` →
 * `renderPage` — and serves the result. No spine, no database, no media:
 * the pure functions that build customer sites, building one in front of
 * you. Deterministic by construction (`identitySeed` is FNV-1a over name +
 * town): run it twice, get the same site — which is the honesty claim the
 * flagship makes out loud, so a test pins it byte-for-byte.
 *
 * The laws of this surface (proposed as ADR-070):
 * - **Taxonomy-exact trade.** The `[trade]` param resolves via
 *   `getTradeDefinition` — exact id or nothing (ADR-066). The fuzzy legacy
 *   matcher never touches a URL.
 * - **The town is sanitised, hard.** It ends up inside generated headings,
 *   so it is letters, spaces, hyphens and apostrophes only, capped, title-
 *   cased — or the route 404s. Visitor-typed words never pass through raw.
 * - **The example says so, permanently.** A strip above the site names it
 *   a generated demonstration; the business name is `Example …` by
 *   construction; metadata is noindex. A fabricated business must never be
 *   mistakable for, or indexed as, a real one (ADR-059 optics).
 * - **Public-mode redaction.** The blueprint's internal direction never
 *   reaches the markup (`mode: "public"`), exactly as on published sites.
 * - **Media absent, honestly.** A synthetic business has no approved
 *   photographs, so the designed empty states render (ADR-034) — which is
 *   itself the product demonstrating its own honesty law.
 */

export interface DemoSiteRequest {
  /** Raw `[trade]` URL segment — must be an exact taxonomy id. */
  readonly trade: string;
  /** Raw `[town]` URL segment — sanitised before any use. */
  readonly town: string;
}

export interface ResolvedDemoSite {
  readonly definition: TradeDefinition;
  /** The sanitised, title-cased town the site was generated for. */
  readonly town: string;
  /** Neutral example naming (PRD-007 Q4): "Example Roofing" etc. */
  readonly businessName: string;
  readonly blueprint: WebsiteBlueprint;
}

/** Letters, spaces, hyphens, apostrophes; 2–40 chars once cleaned. */
function sanitiseTown(raw: string): string | null {
  const spaced = raw.replace(/[-_]+/g, " ");
  if (/[^a-zA-Z' ]/.test(spaced)) return null;
  const cleaned = spaced.replace(/\s+/g, " ").trim();
  if (cleaned.length < 2 || cleaned.length > 40) return null;
  return cleaned
    .split(" ")
    .map((word) => word.charAt(0).toUpperCase() + word.slice(1))
    .join(" ");
}

/** "solar PV" → "Solar PV"; existing capitals (MOT, PV) are respected. */
function titleCase(phrase: string): string {
  return phrase
    .split(" ")
    .map((word) => word.charAt(0).toUpperCase() + word.slice(1))
    .join(" ");
}

/**
 * Resolve a demo request to a generated site, or null when the trade is
 * not an exact taxonomy id or the town fails sanitisation — the route
 * turns null into a 404. Pure and synchronous, like the chain it runs.
 */
export function resolveDemoSite(request: DemoSiteRequest): ResolvedDemoSite | null {
  const definition = getTradeDefinition(request.trade.trim().toLowerCase());
  if (!definition) return null;
  const town = sanitiseTown(request.town);
  if (!town) return null;

  const businessName = `Example ${titleCase(definition.customerName)}`;
  // customerName, not label: the trade string reaches the generated page's
  // own chrome, and "(emergency)" is operational vocabulary (ADR-061).
  // Archetype classification is identical from either string for all 35 —
  // verified before this line changed, pinned by the sweep test below.
  const strategy = generateExperienceStrategy({
    businessName,
    trade: definition.customerName,
    location: town,
  });
  const blueprint = buildWebsiteBlueprint({ strategy });
  return { definition, town, businessName, blueprint };
}

export function WebsiteDemoPage({ resolved }: { resolved: ResolvedDemoSite }) {
  return (
    <div className={rendererFontClass}>
      {/* The permanent truth strip. Not part of the generated site, never
          absent from the document. */}
      <div
        role="note"
        className="flex items-center justify-center gap-2 bg-[#05060a] px-4 py-2 text-center text-xs font-medium tracking-wide text-amber-200"
      >
        Example site — generated by TITAN for demonstration. Not a real
        business.
      </div>
      {/* Single-document demo: internal links are inert anchors in v1.
          A multi-page demo is an ADR-070 consequence, not an accident. */}
      {renderPage(resolved.blueprint, {
        mode: "public",
        onUnmapped: "skip",
        pageHref: () => "#example-demo",
      })}
    </div>
  );
}
